services:
  nginx:
    build: .
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/sites-available/:/etc/nginx/sites-available/:ro
      - ./config/sites-enabled/:/etc/nginx/sites-enabled/:ro
    networks:
      proxy:
        ipv4_address: 172.23.0.2
networks:
  proxy:
    name: proxy
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1