services:
  blog:
    image: 0xarnout/blog:0.1.0
    user: 800:800
    ports:
      - "127.0.0.1:8080:8080/tcp"
    environment:
      DATABASE_URL: mysql://blog@db/blog
      DATABASE_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - type: bind
        source: ./volumes/uploads
        target: /static/uploads
    secrets:
      - db_password
  db:
    image: "mariadb:lts"
    user: 999:999
    environment:
      MARIADB_DATABASE: blog
      MARIADB_USER: blog
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_AUTO_UPGRADE: 1
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
volumes:
  db-data:
secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt